"""Constants for Dummy OS Energy."""

from __future__ import annotations

DOMAIN = "dummy_os_data"
NAME = "Dummy OS Energy"
VERSION = "0.2.0-alpha.18"

# Legacy Energy Forecast source key retained for config-entry compatibility only.
# Energy Forecast production always consumes the canonical Source Home Power entity.
CONF_HOME_POWER_ENTITY = "home_power_entity"
DEFAULT_HOME_POWER_ENTITY = "sensor.home_power"
CANONICAL_HOME_POWER_ENTITY = "sensor.do_source_home_power"
CONF_HOME_POWER_POSITIVE_DIRECTION = "home_power_positive_direction"
HOME_POWER_POSITIVE_CONSUMPTION = "consumption"
HOME_POWER_POSITIVE_EXPORT = "export"
HOME_POWER_POSITIVE_DIRECTION_OPTIONS = [
    HOME_POWER_POSITIVE_CONSUMPTION,
    HOME_POWER_POSITIVE_EXPORT,
]

# Canonical Dummy OS Energy source-layer energy inputs.
# Grid power is one bidirectional source: positive = import, negative = export.
CONF_GRID_NET_POWER_ENTITY = "grid_net_power_entity"
CONF_DATA_SOLAR_POWER_ENTITY = "data_solar_power_entity"
CONF_DATA_BATTERY_CHARGE_POWER_ENTITY = "data_battery_charge_power_entity"
CONF_DATA_BATTERY_DISCHARGE_POWER_ENTITY = "data_battery_discharge_power_entity"

# Legacy split-grid keys are read-only migration inputs.
LEGACY_CONF_GRID_IMPORT_POWER_ENTITY = "grid_import_power_entity"
LEGACY_CONF_GRID_EXPORT_POWER_ENTITY = "grid_export_power_entity"

# Backward-compatible Python aliases for older internal imports.
CONF_GRID_IMPORT_POWER_ENTITY = LEGACY_CONF_GRID_IMPORT_POWER_ENTITY
CONF_GRID_EXPORT_POWER_ENTITY = LEGACY_CONF_GRID_EXPORT_POWER_ENTITY

DEFAULT_GRID_NET_POWER_ENTITY = "sensor.home_grid_power"
DEFAULT_GRID_IMPORT_POWER_ENTITY = "sensor.home_grid_import_power"
DEFAULT_GRID_EXPORT_POWER_ENTITY = "sensor.home_grid_export_power"
DEFAULT_DATA_SOLAR_POWER_ENTITY = "sensor.home_solar_power"
DEFAULT_DATA_BATTERY_CHARGE_POWER_ENTITY = "sensor.home_battery_charge_power"
DEFAULT_DATA_BATTERY_DISCHARGE_POWER_ENTITY = "sensor.home_battery_discharge_power"

CONF_GRID_NET_POWER_POSITIVE_DIRECTION = "grid_net_power_positive_direction"
GRID_NET_POWER_POSITIVE_IMPORT = "import"
GRID_NET_POWER_POSITIVE_EXPORT = "export"
GRID_NET_POWER_POSITIVE_DIRECTION_OPTIONS = [
    GRID_NET_POWER_POSITIVE_IMPORT,
    GRID_NET_POWER_POSITIVE_EXPORT,
]

CONF_BATTERY_CAPACITY_KWH = "battery_capacity_kwh"
CONF_BATTERY_MAX_CHARGE_POWER_W = "battery_max_charge_power_w"
CONF_BATTERY_MAX_DISCHARGE_POWER_W = "battery_max_discharge_power_w"
CONF_BATTERY_MIN_SOC_PERCENT = "battery_min_soc_percent"
CONF_BATTERY_RESERVE_SOC_PERCENT = "battery_reserve_soc_percent"
CONF_BATTERY_EXECUTION_BUFFER_PERCENT = "battery_execution_buffer_percent"
CONF_BATTERY_CHARGE_EFFICIENCY_PERCENT = "battery_charge_efficiency_percent"
CONF_BATTERY_DISCHARGE_EFFICIENCY_PERCENT = "battery_discharge_efficiency_percent"
CONF_BATTERY_SOC_ENTITY = "battery_soc_entity"

DEFAULT_BATTERY_CAPACITY_KWH = 7.2
DEFAULT_BATTERY_MAX_CHARGE_POWER_W = 3200
DEFAULT_BATTERY_MAX_DISCHARGE_POWER_W = 3200
DEFAULT_BATTERY_MIN_SOC_PERCENT = 5.0
DEFAULT_BATTERY_RESERVE_SOC_PERCENT = 7.0
DEFAULT_BATTERY_EXECUTION_BUFFER_PERCENT = 2.0
DEFAULT_BATTERY_CHARGE_EFFICIENCY_PERCENT = 92.0
DEFAULT_BATTERY_DISCHARGE_EFFICIENCY_PERCENT = 92.0
DEFAULT_BATTERY_SOC_ENTITY = "sensor.anker_solix_solarbank_max_ac_185_soc"

CONF_MINIMUM_TRADE_MARGIN = "minimum_trade_margin"
DEFAULT_MINIMUM_TRADE_MARGIN = 0.10

CONF_IMPORT_MARKUP_EUR_KWH = "import_markup_eur_kwh"
CONF_EXPORT_MARKUP_EUR_KWH = "export_markup_eur_kwh"
DEFAULT_IMPORT_MARKUP_EUR_KWH = 0.0
DEFAULT_EXPORT_MARKUP_EUR_KWH = 0.0

CONF_PRICE_RESOLUTION_MINUTES = "price_resolution_minutes"
PRICE_RESOLUTION_OPTIONS = [15, 60]
DEFAULT_PRICE_RESOLUTION_MINUTES = 15

CONF_ELECTRICITY_PRICE_SOURCE = "electricity_price_source"
ELECTRICITY_PRICE_SOURCE_STROOMVOORSPELLER = "stroomvoorspeller"
DEFAULT_ELECTRICITY_PRICE_SOURCE = ELECTRICITY_PRICE_SOURCE_STROOMVOORSPELLER

CONF_GAS_PRICE_EUR_M3 = "gas_price_eur_m3"
CONF_GAS_FIXED_COST_EUR_DAY = "gas_fixed_cost_eur_day"
DEFAULT_GAS_PRICE_EUR_M3 = 1.56
DEFAULT_GAS_FIXED_COST_EUR_DAY = 0.32055

ENERGY_STORE_SCHEMA_VERSION = 2
PROFILE_CONTRACT_VERSION = 1
PROFILE_NORMAL = "normal"
PROFILE_AWAY = "away"
PROFILE_UNCLASSIFIED = "unclassified"
PROFILE_MIXED = "mixed"
PROFILE_LEARNING_OPTIONS = [PROFILE_NORMAL, PROFILE_AWAY]
PROFILE_OPTIONS = [PROFILE_NORMAL, PROFILE_AWAY, PROFILE_UNCLASSIFIED]
FORECAST_HORIZON_HOURS = 72
QUARTER_MINUTES = 15
FORECAST_SLOT_COUNT = int(FORECAST_HORIZON_HOURS * 60 / QUARTER_MINUTES)
